/* Generate promo/ready-to-post.md from the distribution kit.

   The kit is the single source of truth for every string we publish, and the
   copy blocks in it are machine-checked for platform limits and for banned
   claims. This script only lifts two blocks out of it so they can be pasted
   without scrolling through the whole plan — it must never hold wording of
   its own, or there would again be two places to edit.

   Usage:  node _dev/gen-posts.cjs
*/

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const KIT = path.join(ROOT, 'promo', 'distribution-kit.md');
const OUT = path.join(ROOT, 'promo', 'ready-to-post.md');

function blocks(src) {
  const out = new Map();
  const re = /```copy name=([\w-]+)(?: limit=(\d+))?( refutes)?\n([\s\S]*?)```/g;
  let m;
  while ((m = re.exec(src))) out.set(m[1], m[4].replace(/\n$/, ''));
  return out;
}

const kit = fs.readFileSync(KIT, 'utf8');
const b = blocks(kit);

const WANTED = ['devto-post', 'ih-post'];
for (const name of WANTED) {
  if (!b.has(name)) {
    console.error(`gen-posts: block "${name}" is missing from the kit`);
    process.exit(1);
  }
}

const date = new Date().toISOString().slice(0, 10);

const md = `# Ready to post

Generated ${date} by \`node _dev/gen-posts.cjs\` from
\`promo/distribution-kit.md\`. **Do not edit this file** — change the copy in
the kit and re-run the script.

Every figure below was measured by this project's own scripts, and the two
"things I got wrong" paragraphs are the record correcting itself, which is why
they read better than a launch announcement would.

---

## dev.to

The block below is **title on the first line, body starting at the third**. Put
the first line in dev.to's title field and begin the body at "Every image
compressor I tried" — do not repeat the title in the body, because dev.to
renders the title above it already. dev.to takes markdown, so the \`##\`
headings and bullet lists survive as-is.

**Leave the canonical URL field empty.** It is tempting to point it at
\`https://localphototool.com\` so the site gets the credit, but canonical says
"this page is a copy, index that one instead" — Google would drop the post from
its index and the whole point of posting, a page that exists and links to the
site, is gone. Only fill it in if the same text is also published on your own
domain; if dev.to is the only place it appears, dev.to should keep the credit.

\`\`\`
${b.get('devto-post')}
\`\`\`

---

## Indie Hackers

Shorter and blunter. Indie Hackers rewards naming what is going badly, so the
last line keeps distribution as the unsolved part.

\`\`\`
${b.get('ih-post')}
\`\`\`

---

## Where else the same material goes

| Place | Which block from the kit |
| --- | --- |
| Show HN | \`hn-title\` + \`hn-body\` |
| r/SideProject | \`reddit-sideproject-title\` + \`reddit-sideproject-body\` |
| r/privacy | \`reddit-privacy-title\` + \`reddit-privacy-body\` |
| AlternativeTo, directories | \`short\` / \`medium\` |
| awesome-list PRs | \`pr-body\` |

Check the whole kit is still honest before pasting any of it:

\`\`\`
node _dev/check-listing-copy.cjs
\`\`\`
`;

fs.writeFileSync(OUT, md, { encoding: 'utf8' });
console.log(`gen-posts: wrote ${path.relative(ROOT, OUT)}`);
console.log(`  devto-post ${b.get('devto-post').length} chars`);
console.log(`  ih-post    ${b.get('ih-post').length} chars`);
