/* PWA checks in a real browser:
     - the manifest is valid and every icon it lists really loads
     - the service worker registers and takes control
     - the compress page still works with the network switched off
     - a phone that swipes sideways cannot drag the page out of the viewport
     - results scroll into view after a batch is added
   Run: node _dev/test-pwa.cjs                                             */
const fs = require('fs');
const path = require('path');
const { spawn } = require('child_process');
const { chromium } = require(path.join('C:/Users/Administrator/.workbuddy/binaries/node/workspace/node_modules/playwright-core'));

/* 8893 is taken by test-heic, and two suites sharing a port is a flake waiting
   for a slow kill: whichever runs second talks to the other's server. */
const PORT = 8894;
const BASE = 'http://127.0.0.1:' + PORT;
const SITE = path.join(__dirname, '..', 'localphototool');
const CHROME = 'C:/Users/Administrator/AppData/Local/ms-playwright/chromium_headless_shell-1243/chrome-headless-shell-win64/chrome-headless-shell.exe';
const UA_PHONE = 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1';

let pass = 0, fail = 0;
function ok(name, cond, extra) {
  if (cond) { pass++; console.log('  PASS  ' + name); }
  else { fail++; console.log('  FAIL  ' + name + (extra !== undefined ? '  → ' + extra : '')); }
}
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

/* A real, decodable PNG generated by the browser itself — no fixture files. */
async function makePng(page, w, h, seed) {
  const dataUrl = await page.evaluate(({ w, h, seed }) => {
    const c = document.createElement('canvas');
    c.width = w; c.height = h;
    const g = c.getContext('2d');
    const grad = g.createLinearGradient(0, 0, w, h);
    grad.addColorStop(0, 'hsl(' + seed + ' 70% 55%)');
    grad.addColorStop(1, 'hsl(' + ((seed + 90) % 360) + ' 70% 35%)');
    g.fillStyle = grad;
    g.fillRect(0, 0, w, h);
    for (let i = 0; i < 60; i++) {
      g.fillStyle = 'rgba(255,255,255,' + (0.05 + (i % 5) * 0.05) + ')';
      g.fillRect((i * 37) % w, (i * 53) % h, 24, 18);
    }
    return c.toDataURL('image/png');
  }, { w, h, seed });
  return Buffer.from(dataUrl.split(',')[1], 'base64');
}

(async () => {
  const server = spawn(process.execPath, [path.join(__dirname, 'serve-site.cjs')], {
    env: Object.assign({}, process.env, { PORT: String(PORT) }), stdio: 'ignore'
  });
  await sleep(800);

  const browser = await chromium.launch({ executablePath: CHROME, args: ['--no-sandbox'] });

  try {
    console.log('\nPWA / mobile layout — browser tests\n');

    const fixturePage = await browser.newPage();
    const PNG = await makePng(fixturePage, 320, 240, 210);
    const PNG2 = await makePng(fixturePage, 400, 300, 30);
    await fixturePage.close();
    ok('test fixture: a real PNG was generated', PNG.length > 500, PNG.length + ' bytes');

    /* ---- 1. manifest + icons ---------------------------------------- */
    const mf = JSON.parse(fs.readFileSync(path.join(SITE, 'site.webmanifest'), 'utf8'));
    ok('manifest declares a standalone display', mf.display === 'standalone');
    ok('manifest declares a start_url and scope', !!mf.start_url && !!mf.scope);
    const sizes = mf.icons.map((i) => i.sizes);
    ok('manifest has a 192px icon', sizes.indexOf('192x192') !== -1);
    ok('manifest has a 512px icon', sizes.indexOf('512x512') !== -1);
    ok('manifest has a maskable icon',
      mf.icons.some((i) => String(i.purpose).indexOf('maskable') !== -1));

    const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, userAgent: UA_PHONE, deviceScaleFactor: 2 });
    const page = await ctx.newPage();
    for (const icon of mf.icons) {
      const r = await page.request.get(BASE + icon.src);
      ok('icon loads: ' + icon.src, r.status() === 200, 'status ' + r.status());
    }
    const man = await page.request.get(BASE + '/site.webmanifest');
    ok('manifest is served with a JSON content type',
      String(man.headers()['content-type'] || '').indexOf('json') !== -1,
      man.headers()['content-type']);

    /* ---- 2. every page links the manifest and pwa script ------------- */
    for (const p of ['/', '/compress/', '/about/', '/privacy/', '/terms/']) {
      const html = await (await page.request.get(BASE + p)).text();
      ok(p + ' links the manifest', html.indexOf('rel="manifest"') !== -1);
      ok(p + ' loads pwa.js', html.indexOf('pwa.js') !== -1);
      ok(p + ' has the iOS home-screen meta', html.indexOf('apple-mobile-web-app-capable') !== -1);
    }

    /* ---- 3. service worker registers and controls the page ----------- */
    await page.goto(BASE + '/compress/', { waitUntil: 'load' });
    await page.waitForFunction(() => navigator.serviceWorker.controller !== null, { timeout: 15000 })
      .catch(() => {});
    const swState = await page.evaluate(async () => {
      const reg = await navigator.serviceWorker.getRegistration();
      return {
        hasSW: 'serviceWorker' in navigator,
        scope: reg ? reg.scope : null,
        active: !!(reg && reg.active),
        controlled: !!navigator.serviceWorker.controller,
        caches: await caches.keys()
      };
    });
    ok('service worker is active', swState.active === true, JSON.stringify(swState));
    ok('service worker controls the page', swState.controlled === true);
    ok('scope covers the whole site', String(swState.scope || '').endsWith('/'));
    ok('app shell is precached', swState.caches.some((c) => c.indexOf('lpt-shell') === 0), swState.caches.join(','));

    const cached = await page.evaluate(async () => {
      const names = await caches.keys();
      const out = [];
      for (const n of names) {
        const c = await caches.open(n);
        const keys = await c.keys();
        out.push(...keys.map((r) => new URL(r.url).pathname));
      }
      return out;
    });
    ok('the compressor is available offline', cached.indexOf('/compress/') !== -1);
    ok('the WASM worker is precached', cached.indexOf('/assets/js/compressor/worker.js') !== -1);

    /* ---- 4. offline: the tool still loads and compresses -------------- */
    const offlineCtx = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, userAgent: UA_PHONE });
    const offPage = await offlineCtx.newPage();
    await offPage.goto(BASE + '/compress/', { waitUntil: 'load' });
    await offPage.waitForFunction(() => navigator.serviceWorker.controller !== null, { timeout: 15000 }).catch(() => {});
    await offPage.waitForTimeout(800);
    await offlineCtx.setOffline(true);
    await offPage.reload({ waitUntil: 'load' });
    await offPage.waitForTimeout(700);
    const offlineTitle = await offPage.title();
    const offlineHasDrop = await offPage.$('#dropzone') !== null;
    ok('offline reload still serves the compressor', offlineHasDrop === true, offlineTitle);
    if (offlineHasDrop) {
      await offPage.setInputFiles('#fileInput', [{ name: 'offline.png', mimeType: 'image/png', buffer: PNG }]);
      const offlineDone = await offPage.waitForSelector('.result__saved, .result__grew', { timeout: 25000 })
        .then(() => true).catch(() => false);
      ok('a file compresses with no network at all', offlineDone === true);
      const offlineOut = await offPage.$$eval('.result__meta', (els) => els.map((e) => e.innerText.replace(/\s+/g, ' ').trim()));
      ok('offline output reports a real size', offlineOut.length > 0 && /→/.test(offlineOut[0]), offlineOut.join(' | '));
      await offPage.screenshot({ path: path.join(__dirname, 'out', 'pwa-offline-compress.png') });
    } else {
      ok('a file compresses with no network at all', false, 'page did not load offline');
    }

    /* ---- 4b. an uncached page while offline must reach the offline page ----
       The shell above is served from the page cache, which hides a real trap:
       Cloudflare Pages answers /offline.html with a 308 to /offline, and a
       browser refuses to answer a NAVIGATION request with a response that came
       through a redirect. Had the service worker stored that hop verbatim, this
       request would die with a network error instead of the offline page. */
    const reached = await offPage.goto(BASE + '/not-cached-' + Date.now() + '/', { waitUntil: 'load' })
      .then(() => true).catch(() => false);
    await offPage.waitForTimeout(400);
    const fallbackTitle = await offPage.title().catch(() => '');
    const hasOfflineMark = await offPage.$('.offline__mark').then((el) => el !== null).catch(() => false);
    ok('an uncached page while offline shows the offline fallback',
      reached && hasOfflineMark && /offline/i.test(fallbackTitle),
      (reached ? '' : 'navigation failed ') + 'title: ' + fallbackTitle);
    await offPage.screenshot({ path: path.join(__dirname, 'out', 'pwa-offline-fallback.png') });

    await offlineCtx.close();

    /* ---- 5. no sideways panning on a phone ---------------------------- */
    for (const p of ['/', '/compress/', '/about/', '/privacy/', '/terms/']) {
      await page.goto(BASE + p, { waitUntil: 'load' });
      await sleep(400);
      const m = await page.evaluate(() => {
        const d = document.documentElement;
        const scrollable = d.scrollWidth - d.clientWidth;
        const canPan = getComputedStyle(d).overflowX;
        return { scrollable, canPan, bodyOverflow: getComputedStyle(document.body).overflowX };
      });
      ok(p + ' has no horizontal overflow', m.scrollable <= 1, 'scrollWidth-clientWidth = ' + m.scrollable);
      ok(p + ' locks horizontal panning', m.canPan === 'clip' || m.canPan === 'hidden', m.canPan);
    }
    const overscroll = await page.evaluate(() => getComputedStyle(document.documentElement).overscrollBehaviorX);
    ok('horizontal rubber-banding is disabled', overscroll === 'none', overscroll);

    /* ---- 6. adding files scrolls the results into view ---------------- */
    await page.goto(BASE + '/compress/', { waitUntil: 'load' });
    await sleep(500);
    const beforeY = await page.evaluate(() => window.scrollY);
    await page.setInputFiles('#fileInput', [
      { name: 'a.png', mimeType: 'image/png', buffer: PNG },
      { name: 'b.png', mimeType: 'image/png', buffer: PNG2 }
    ]);
    const done = await page.waitForSelector('.result__saved, .result__grew', { timeout: 25000 })
      .then(() => true).catch(() => false);
    ok('both files compress', done === true);
    await page.waitForTimeout(1600);
    const after = await page.evaluate(() => {
      const r = document.getElementById('results');
      const box = r.getBoundingClientRect();
      return { scrollY: window.scrollY, top: Math.round(box.top), hidden: r.hidden, vh: window.innerHeight };
    });
    ok('results are revealed after adding files', after.hidden === false);
    ok('the page scrolled down to the results', after.scrollY > beforeY, 'scrollY ' + beforeY + ' → ' + after.scrollY);
    ok('the results heading is on screen',
      after.top >= -4 && after.top < after.vh, 'top=' + after.top);
    await page.screenshot({ path: path.join(__dirname, 'out', 'pwa-results-scroll.png') });

    /* ---- 7. install entry --------------------------------------------- */
    const installIOS = await page.evaluate(() => {
      const b = document.getElementById('installApp');
      return b ? { exists: true, hidden: b.hidden, label: b.getAttribute('aria-label') } : { exists: false };
    });
    ok('phone shows an install entry', installIOS.exists === true && installIOS.hidden === false, JSON.stringify(installIOS));
    if (installIOS.exists) {
      await page.click('#installApp');
      await page.waitForTimeout(400);
      const guide = await page.evaluate(() => {
        const g = document.getElementById('installGuide');
        return g ? { open: !g.hidden, text: g.innerText.replace(/\s+/g, ' ').slice(0, 120) } : { open: false };
      });
      ok('iOS gets written instructions instead of a dead button', guide.open === true, JSON.stringify(guide));
      await page.screenshot({ path: path.join(__dirname, 'out', 'pwa-install-guide.png') });
      const closed = await page.evaluate(() => {
        document.querySelector('#installGuide [data-close]').click();
        return document.getElementById('installGuide').hidden;
      });
      ok('the instructions can be dismissed', closed === true);
    }

    await ctx.close();
  } catch (e) {
    fail++;
    console.log('  FAIL  unexpected error → ' + (e && e.stack || e));
  } finally {
    await browser.close();
    server.kill();
  }

  console.log('\n' + pass + ' passed, ' + fail + ' failed\n');
  process.exit(fail ? 1 : 0);
})();
